<?php
    $title = "Adicionando Pessoas";
?>

<h1><?= $this->escapeHtml($title)?></h1>

<?php
$form->setAttribute('action',$this->url('an-categoria-val',['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);
$id = $this->form->get('id');
$descricao = $this->form->get('descricao');

$descricao->setAttribute('class','form-control');
$descricao->setAttribute('auto-focus','auto-focus');

$submit = $this->form->get('submit');
$submit->setAttribute('class','btn btn-primary btn-lg');
?>

<?=$this->formElement($id)?>
<div class="form-group">
    <div class="col-md-4">
        <?=$this->formLabel($descricao)?>
        <?=$this->formElement($descricao)?>
        <?=$this->formElementErrors()->render($descricao,['class' => 'help-desk'])?>
    </div>
</div>

<div class="row">
    <?=$this->formElement($submit)?>
    <a class="btn btn-warning" href="<?=$this->url('an-categoria-val',['action' => 'index'])?>">Voltar</a>
</div>

