<h1>Minha View anCategoriaVal</h1>

<table class="table table-stripped">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
       

        
    </tr>
    <?php
    
        foreach($anCategoriaVals as $anCategoriaVal):
        ?>
           <tr>
                <td><?=$anCategoriaVal->getId()?></td>
                <td><?=$anCategoriaVal->getDescricao()?></td>
                
                
            </tr>   
        <?php
        endforeach;    
        
    ?>
</table>
<div class="row">
    
    <a class="btn btn-warning" href="<?=$this->url('an-categoria-val',['action' => 'adicionar'])?>">Adicionar</a>
</div>