<?php
$title = "Adicionando nova Pessoa";
$this->headTitle($title);
?>

<h1><?=$this->escapeHtml($title)?></h1>

<?php
$form->setAttribute('action',$this->url('produto',['action' => 'adicionar']));
$form->prepare();

echo $this->form()->openTag($form);
$id = $this->form->get('id');
$nome = $this->form->get('nome');
$tipo = $this->form->get('tipo');
$situacao = $this->form->get('situacao');

$nome->setAttribute('class','form-control');
$tipo->setAttribute('class','form-control');
$situacao->setAttribute('class','form-control');
$nome->setAttribute('autofocus','autofocus');

$submit = $this->form->get('submit');
$submit->setAttribute('class','btn btn-primary btn-lg');
?>

<div class="row">
    <?=$this->formElement($submit)?>
</div>

<?=$this->formElement($id)?>
<div class="form-group">
    <div class="col-md-4">
        <?=$this->formLabel($nome)?>
        <?=$this->formElement($nome)?>
        <?=$this->formElementErrors()->render($nome,['class' => 'help-block'])?>
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        <?=$this->formLabel($tipo)?>
        <?=$this->formElement($tipo)?>
        <?=$this->formElementErrors()->render($tipo,['class' => 'help-block'])?>
    </div>
</div>

<div class="form-group">
    <div class="col-md-4">
        <?=$this->formLabel($situacao)?>
        <?=$this->formElement($situacao)?>
        <?=$this->formElementErrors()->render($situacao,['class' => 'help-block'])?>
    </div>
</div>

<div class="row">
    <?=$this->formElement($submit)?>
    <a class="btn btn-warning" href="<?=$this->url('produto',['action' => 'index'])?>">Voltar</a>
</div>


