<?php 
$title = "Adicionando Pessoa";
$this->headTitle($title);
?>

<h1><?=$this->escapeHtml($title)?></h1>

<?php

    $form->setAttribute('action',$this->url('ad-cliente',['action' => 'adicionar']));
    $form->prepare();

    echo $this->form()->openTag($form);
    $id = $this->form->get('id');
    $nome = $this->form->get('nome');
    $apelido = $this->form->get('apelido');

    $nome->setAttribute('class','form-control');
    $apelido->setAttribute('class','form-control');
    $nome->setAttribute('autofocus','autofocus');

    $submit = $this->form->get('submit');
    $submit->setAttribute('class','btn btn-primary btn-lg');

?>


<div class="row">
<?=$this->formElement($id)?>
    <?=$this->formElement($submit)?>
</div>

<div class="form-group">
    <div class="col-md-4">
        <?=$this->formLabel($nome)?>
        <?=$this->formElement($nome)?>
        <?=$this->formElementErrors()->render($nome,['class' => 'help-block'])?>
    </div>
</div>

<div class="form-group">
    <div class="col-md-4">
        <?=$this->formLabel($apelido)?>
        <?=$this->formElement($apelido)?>
        <?=$this->formElementErrors()->render($apelido,['class' => 'help-block'])?>
    </div>
</div>


<div class="row">
    <?=$this->formElement($submit)?>
    <a class="btn btn-warning" href="<?=$this->url('ad-cliente',['action' => 'index'])?>">Voltar</a>
</div>