<h1>Minha View adCliente</h1>

<table class="table table-stripped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Apelido</th>

        
    </tr>
    <?php
    
        foreach($adClientes as $adCliente):
        ?>
           <tr>
                <td><?=$adCliente->getId()?></td>
                <td><?=$adCliente->getNome()?></td>
                <td><?=$adCliente->getApelido()?></td>
                
            </tr>   
        <?php
        endforeach;    
        
    ?>
</table>