<h1>Minha View anClassificacaos</h1>

<table class="table table-stripped">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Código</th>
       

        
    </tr>
    <?php
    
        foreach($anClassificacaos as $anClassificacao):
        ?>
           <tr>
                <td><?=$anClassificacao->getId()?></td>
                <td><?=$anClassificacao->getDescricao()?></td>
                <td><?=$anClassificacao->getCodigo()?></td>
                               
            </tr>   
        <?php
        endforeach;    
        
    ?>
</table>

<div class="row">
    
    <a class="btn btn-warning" href="<?=$this->url('an-classificacao',['action' => 'adicionar'])?>">Adicionar</a>
</div>